version: '1'

services:
  usersapiapp:
    image: usersapi
    container_name: usersapiapp
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 7070:8080
    networks:
      - mybridgenetwork
    restart: always

  postgres:
    image: postgres
    container_name: postgresdb
    environment:
      - POSTGRES_USER=emil
      - POSTGRES_PASSWORD=Secret123!
      - POSTGRES_DB=library
    networks:
      - mybridgenetwork
    ports:
      - 5432:5432
    expose:
      - 5432



networks:
  mybridgenetwork:
    name: books-api_mybridgenetwork
    external: true
  