version: '1'

services:
  usersapiapp:
    image: usersapi
    container_name: usersapiapp
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 7070:8080
    networks:
      - mybridgenetwork
    restart: always



networks:
  mybridgenetwork:
    name: books-api_mybridgenetwork
    external: true
  